Make bin/ooniprobe-dev portable
- use a portable recipe to get the absolute path of the toplevel
  directory where ooni-probe sources are located [1]

- make sure we exit with a meaningful error message if it is not
  possible to get the toplevel directory name

- while there put quotes around $@ since according to [2] this
  is the best way to forward shell script arguments

.. [1] http://serverfault.com/questions/40144

.. [2] http://stackoverflow.com/questions/255898/how-to-iterate-over-arguments-in-bash-script/256225#256225

diff --git a/bin/ooniprobe-dev b/bin/ooniprobe-dev
--- a/bin/ooniprobe-dev
+++ b/bin/ooniprobe-dev
@@ -2,5 +2,9 @@
 # Developer script for running ooniprobe directly from the repository.
 # We don't automatically add "$PWD" to PYTHONPATH as that is a security risk
 # when run as /usr/bin/ooniprobe on an end user's computer.
-cd "$(realpath "$(dirname "$0")")/.."
-PYTHONPATH="$PWD" exec ./bin/ooniprobe $@
+ROOTDIR=$(cd $(dirname $(dirname $0)) && pwd -P)
+if [ $? -ne 0 ]; then
+    echo "$0: cannot determine toplevel directory" 1>&2
+    exit 1
+fi
+PYTHONPATH="$ROOTDIR" exec ./bin/ooniprobe "$@"
